In [1]:
import pandas as pd

rename_cols = {
    'Unnamed: 5': 'home_team',
    'Unnamed: 7': 'boxscore',
    'Week ': 'week',
    'Winner/tie ': 't1',
    'Loser/tie ': 't2',
    'PtsW ': 's1',
    'PtsL ': 's2',
    'TOW ': 'to1',
    'TOL': 'to2',
    'YdsW ': 'yd1',
    'YdsL ': 'yd2'
    
}
columns = ['t1', 't2', 's1', 's2', 'yd1', 'yd2', 'to1', 'to2', 'home_team', 'week']
df = pd.read_csv('./2009-raw.tsv', sep='\t').rename(columns=rename_cols)[columns]
df.t1 = df.t1.apply(lambda s: s.split(' ')[-1].strip())
df.t2 = df.t2.apply(lambda s: s.split(' ')[-1].strip())
df.home_team = df.apply(lambda r: r.t2 if pd.notna(r.home_team) and r.home_team.strip() == '@' else r.t1, axis=1)

df

           t1          t2  s1  s2  yd1  yd2  to1  to2   home_team  week
0    Steelers      Titans  13  10  357  320    3  2.0    Steelers     1
1     Broncos     Bengals  12   7  302  307    0  2.0     Bengals     1
2      Ravens      Chiefs  38  24  501  188    1  0.0      Ravens     1
3       Colts     Jaguars  14  12  365  228    2  0.0       Colts     1
4     Cowboys  Buccaneers  34  21  462  450    0  0.0  Buccaneers     1
..        ...         ...  ..  ..  ...  ...  ...  ...         ...   ...
251   Cowboys      Eagles  24   0  474  228    1  1.0     Cowboys    17
252    Chiefs     Broncos  44  24  524  512    2  3.0     Broncos    17
253    Ravens     Raiders  21  13  330  325    0  2.0     Raiders    17
254    Titans    Seahawks  17  13  304  309    2  1.0    Seahawks    17
255      Jets     Bengals  37   0  320   72    0  3.0        Jets    17

[256 rows x 10 columns]

In [2]:
teams = sorted(list(set(df.t1) | set(df.t2)))
print(len(teams))
print(teams)

32
['49ers', 'Bears', 'Bengals', 'Bills', 'Broncos', 'Browns', 'Buccaneers', 'Cardinals', 'Chargers', 'Chiefs', 'Colts', 'Cowboys', 'Dolphins', 'Eagles', 'Falcons', 'Giants', 'Jaguars', 'Jets', 'Lions', 'Packers', 'Panthers', 'Patriots', 'Raiders', 'Rams', 'Ravens', 'Redskins', 'Saints', 'Seahawks', 'Steelers', 'Texans', 'Titans', 'Vikings']

In [3]:
df.to_csv('2009.csv', index=False)